version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data_container:/data/db
  mongo_seed:
    image: mongo:latest
    links:
      - mongodb_container
    volumes:
      - ./mongo-seed:/mongo-seed
    command: /mongo-seed/mongo-import.sh

volumes:
  mongodb_data_container:
  mongo-seed:
